### ISSUE TITLE
Pagination component page input needs debounce

### ISSUE THREAD

**Issue by AllenBW** [RedHatInsights/insights-frontend-components#149]
Title says it all, on input, instantly whatever function is tied to the input, is executed, there should be a little pause on input so users can type long numbers 😋 

![test](https://user-images.githubusercontent.com/6640236/48562822-fc5b3200-e8c0-11e8-8511-b4aadba1e840.gif)

**Comment by karelhala** [comment]
Sadly this cannot be fixed in frontend components because of how pagination works with input. If we'd were to add debounce here page number wouldn't change until debounce finishes, that is a no-go and is really bad. We could work around this, but it would add a lot of custom logic that would need to be updated once we start using PF4 pagination. However I am gonna write doc example on how to work with this because now we are passing additional argument to tell consumers that they should debounce.

**Comment by karelhala** [comment]
https://github.com/RedHatInsights/insights-frontend-components/pull/248

**Comment by AllenBW** [comment]
Drat, I was hoping this wouldn't be the solution, means more changes in other places, but thanks for following up @karelhala !! #248 is a great piece of work 🤗
